version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: article-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: article_db
      MYSQL_USER: article_user
      MYSQL_PASSWORD: article_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: article-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: article_user
      DB_PASSWORD: article_pass
      DB_NAME: article_db
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8080:8080"
    command: ["./article-service"]

volumes:
  db_data: