version: "3.8"

services:
  article-db:
    image: postgres:15
    container_name: article-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: articles
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d articles"]
      interval: 5s
      timeout: 5s
      retries: 5

  article-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: article-api
    depends_on:
      article-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@article-db:5432/articles?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db-data:
